### ISSUE TITLE
MacOS Sequoia - Crashing on startup

### ISSUE THREAD

**Issue by VIDGuide** [SVGify/SVGify.github.io#1]
Since updating to MacOS Sequoia (15.0.1) SVGify now crashes on startup every time. 

`Process:               SVGify [19303]
Path:                  /Applications/SVGify.app/Contents/MacOS/SVGify
Identifier:            io.cyris.svgify
Version:               1.0.0 (1.0.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-10-11 10:01:38.7269 +1100
OS Version:            macOS 15.0.1 (24A348)
Report Version:        12
Anonymous UUID:        1B1643E0-D5B4-D277-92B2-342769F477C1

Sleep/Wake UUID:       8E69E61C-0A97-4BD8-940E-A9F662C03C8F

Time Awake Since Boot: 43000 seconds
Time Since Wake:       4765 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x0000000115829728

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [19303]`

`Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread
0   Electron Framework            	       0x115829728 electron::fuses::IsLoadBrowserProcessSpecificV8SnapshotEnabled() + 45844
1   Electron Framework            	       0x115829728 electron::fuses::IsLoadBrowserProcessSpecificV8SnapshotEnabled() + 45844
2   Electron Framework            	       0x11583f0c4 v8::internal::GetCurrentStackPosition() + 35436
3   libcache.dylib                	       0x1a5804d38 _value_entry_table_resize + 564
4   libcache.dylib                	       0x1a5805028 cache_set_and_retain + 608
5   CoreFoundation                	       0x197e4f58c -[NSCache setObject:forKey:cost:] + 396
6   CoreText                      	       0x19a5f2e54 TCGFontCache::CopyFont(__CFURL const*, __CFString const*, __CFString const*) + 196
7   CoreText                      	       0x19a4ca0f8 TBaseFont::CopyNativeFont() const + 232
8   CoreText                      	       0x19a5e5788 TTenuousComponentFont::InitializeVariationGraphicsFont() const + 108
9   CoreText                      	       0x19a4d345c TTenuousComponentFont::GetGraphicsFont() const + 56
10  CoreText                      	       0x19a530e4c TBaseFont::GetInitializedGraphicsFont() const + 68
11  CoreText                      	       0x19a5df578 TBaseFont::CalculateFontMetrics(bool, double) const + 48
12  CoreText                      	       0x19a5e3960 TComponentFont::CalculateFontMetrics(bool, double) const + 84
13  CoreText                      	       0x19a5df96c TBaseFont::InitFontMetrics(double) const + 128
14  CoreText                      	       0x19a4c9f1c TBaseFont::GetStrikeMetrics(double, CGAffineTransform const*, bool) const + 172
15  CoreText                      	       0x19a56afac TFont::GetStrikeMetrics(bool) const + 228
16  CoreText                      	       0x19a4c9c6c TFont::InitStrikeMetrics() const + 52
17  CoreText                      	       0x19a4c9c20 CTFontGetAscent + 40
18  UIFoundation                  	       0x19cd632c4 -[__NSFontExtraData initWithFont:] + 116
19  UIFoundation                  	       0x19ce15aa4 __CTFontGetExtraData + 56
20  UIFoundation                  	       0x19cd631e8 -[NSFont initWithTypefaceInfo:key:renderingMode:] + 52
21  UIFoundation                  	       0x19cd63000 -[__NSFontTypefaceInfo fontInstanceForKey:renderingMode:] + 108
22  UIFoundation                  	       0x19cd62f68 -[__NSFontTypefaceInfo fontInstanceForFontDescriptor:size:affineTransform:renderingMode:] + 280
23  UIFoundation                  	       0x19cd622b0 __NSGetMetaFontInstanceWithType + 532
24  AppKit                        	       0x19c2582a8 -[NSMenuBarItemView _effectiveFontRespectingPreferredParameters:] + 184
25  AppKit                        	       0x19c257498 -[NSMenuBarItemView _ensureValidLineCache] + 128
26  AppKit                        	       0x19c256d54 -[NSMenuBarItemView drawRect:] + 112
27  AppKit                        	       0x19bad90c8 _NSViewDrawRect + 160
28  AppKit                        	       0x19c4625a8 -[NSView _recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 1084
29  AppKit                        	       0x19bad8abc -[NSView(NSLayerKitGlue) _drawViewBackingLayer:inContext:drawingHandler:] + 536
30  AppKit                        	       0x19c127d40 -[NSViewBackingLayer drawInContext:] + 56
31  AppKit                        	       0x19bd18650 0x19b98a000 + 3728976
32  AppKit                        	       0x19bdc634c 0x19b98a000 + 4440908
33  AppKit                        	       0x19bdc18b4 0x19b98a000 + 4421812
34  AppKit                        	       0x19bdc5f2c 0x19b98a000 + 4439852
35  AppKit                        	       0x19bdc3a9c 0x19b98a000 + 4430492
36  AppKit                        	       0x19be2dddc 0x19b98a000 + 4865500
37  AppKit                        	       0x19be2e18c 0x19b98a000 + 4866444
38  AppKit                        	       0x19c12796c -[NSViewBackingLayer display] + 1272
39  QuartzCore                    	       0x1a08cb81c CA::Layer::display_if_needed(CA::Transaction*) + 784
40  QuartzCore                    	       0x1a0a58ea4 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 528
41  QuartzCore                    	       0x1a08addb0 CA::Transaction::commit() + 648
42  AppKit                        	       0x19bae83e8 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 272
43  AppKit                        	       0x19c4a3e8c ___NSRunLoopObserverCreateWithHandler_block_invoke + 64
44  CoreFoundation                	       0x197e817a8 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
45  CoreFoundation                	       0x197e81694 __CFRunLoopDoObservers + 552
46  CoreFoundation                	       0x197e80cc4 __CFRunLoopRun + 788
47  CoreFoundation                	       0x197e80334 CFRunLoopRunSpecific + 572
48  HIToolbox                     	       0x1a32b90cc RunCurrentEventLoopInMode + 292
49  HIToolbox                     	       0x1a32bed1c ReceiveNextEventCommon + 220
50  HIToolbox                     	       0x1a32bf020 _BlockUntilNextEventMatchingListInModeWithFilter + 76
51  AppKit                        	       0x19b9c4a70 _DPSNextEvent + 660
52  AppKit                        	       0x19c2ea7b8 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
53  AppKit                        	       0x19b9b7b7c -[NSApplication run] + 480
54  Electron Framework            	       0x118991e20 node::GetArrayBufferAllocator(node::IsolateData*) + 17970108
55  Electron Framework            	       0x11898fc8c node::GetArrayBufferAllocator(node::IsolateData*) + 17961512
56  Electron Framework            	       0x1189489dc node::GetArrayBufferAllocator(node::IsolateData*) + 17670008
57  Electron Framework            	       0x11890f5c4 node::GetArrayBufferAllocator(node::IsolateData*) + 17435488
58  Electron Framework            	       0x117aa2b6c node::GetArrayBufferAllocator(node::IsolateData*) + 2310408
59  Electron Framework            	       0x117aa4604 node::GetArrayBufferAllocator(node::IsolateData*) + 2317216
60  Electron Framework            	       0x117aa04dc node::GetArrayBufferAllocator(node::IsolateData*) + 2300536
61  Electron Framework            	       0x11593cc78 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 13948
62  Electron Framework            	       0x11593dde0 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 18404
63  Electron Framework            	       0x11593dc10 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 17940
64  Electron Framework            	       0x11593c4bc v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 11968
65  Electron Framework            	       0x11593c65c v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 12384
66  Electron Framework            	       0x11560e2f0 ElectronMain + 128
67  dyld                          	       0x197a18274 start + 2840`

**Comment by CyrisXD** [comment]
Thanks for brining this to my attention, I've just published a [new release](https://github.com/SVGify/SVGify.github.io/releases/tag/v1.0.1) which should fix this issue. Let me know if it's working for you.

**Comment by VIDGuide** [comment]
Legend, thanks, I can confirm 1.0.1 is working correctly again. Thanks :)
